// 与java层RCTPullToRefreshScrollView的State名称保持一致
const STATE_RESET = "RESET";
const STATE_PULL_TO_REFRESH = "PULL_TO_REFRESH";
const STATE_RELEASE_TO_REFRESH = "RELEASE_TO_REFRESH";
const STATE_REFRESHING = "REFRESHING";
const STATE_MANUAL_REFRESHING = "MANUAL_REFRESHING";
const STATE_OVERSCROLLING = "OVER_SCROLLING";

module.exports.STATE_RESET = STATE_RESET;
module.exports.STATE_PULL_TO_REFRESH = STATE_PULL_TO_REFRESH;
module.exports.STATE_RELEASE_TO_REFRESH = STATE_RELEASE_TO_REFRESH;
module.exports.STATE_REFRESHING = STATE_REFRESHING;
module.exports.STATE_MANUAL_REFRESHING = STATE_MANUAL_REFRESHING;
module.exports.STATE_OVERSCROLLING = STATE_OVERSCROLLING;
